name: Build Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: echo 'starting deployment pipeline'
      - uses: actions/checkout@v3
        name: checkout code
      - run: pwd
      - run: ls 
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        id: netlify
        name: deploy to netlify
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 4683c5bf-0c7e-4cf7-8d1f-cea16ff8c99f
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'dist'
      - name: deployment summary
        run: |
          echo ${{steps.netlify.outputs.NETLIFY_PREVIEW_URL }}