name: Build Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: hello
      run: |
        echo 'hello world'
